version: "3.9"

services:
  app:
    build: .
    command: yarn run start:dev
    container_name: nestjs
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./app/src:/app/src
      - ./app/node_modules:/app/node_modules


  # redis:
  #   image: redis:alpine
  #   command: redis-server --port 6379
  #   ports:
  #     - 6379:6379
  #   restart: always